version: "3.9"

services:
  app:
    container_name: fastapi_app
    build: .
    ports:
      - "8888:8000"
    command: bash -c "sleep 2 && alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --reload"
    env_file:
      - .env
    depends_on:
      - myadmin
      - redis
      - db

  db:
    image: mysql:8.4
    container_name: db_app
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT:-3306}:${MYSQL_PORT:-3306}"
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    tty: true
    stdin_open: true

  myadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: myadmin_app
    restart: unless-stopped
    ports:
      - "8080:80"
    links:
      - db
    depends_on:
      - db
    env_file:
      - .env
    environment:
      PMA_HOST: db
      PMA_USER: huckparseruser
      PMA_PASSWORD: QQqq11!!

  redis:
    image: redis:7
    container_name: redis_app
    env_file:
      - .env
    command: --port ${REDIS_PORT:-6379}
    expose:
      - "${REDIS_PORT:-6379}"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
